#ifndef GROUP_MANAGEMENT_CONSTANTS_H
#define GROUP_MANAGEMENT_CONSTANTS_H

#define MAX_GROUPS 100
#define MAX_USERS 100
#define MAX_NAME_LENGTH 50
#define MAX_IP_LENGTH 16
#define YAML_FILE_NAME "groups.yaml"

#endif // GROUP_MANAGEMENT_CONSTANTS_H
